spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yeeunn99
  jpa:
    show-sql: true